### ISSUE TITLE
关于这个有问题想要请教一下

### ISSUE THREAD

**Issue by hansuo1223** [bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF#13]
就是在我训练完成后对生成的.out文件做评估的时候，也就是sh run_eval.sh的时候，报这个错
unexpected number of features: 1 (3)
能问下这是什么原因吗？谢谢了

**Comment by hansuo1223** [comment]
I am following your steps，and I have not modified any place.However,when I envaluate .out file(It is the third step),it's has a error "unexpected number of features: 1 (3)" .I can't understand it.I hope you can help me. I would appreciate it that if you can help me!!

**Comment by bamtercelboo** [comment]
您好，这个问题已经有很多同学遇到了，具体原因我也没搞清楚，但是问题出现在那个文件上面，可能是文件格式或者是文件编码的问题，我的解决办法就是用我data下面的out文件。有的人会有这个问题，有的就没有。在文件上多尝试一下解决办法。thanks for your attention.
