### ISSUE TITLE
有试过转Onnx再转TensorRT加速么

### ISSUE THREAD

**Issue by jamesguo** [bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF#15]

**Comment by jamesguo** [comment]
onnx转tensorrt Gather 遇到Assertion failed: !(data->getType() == nvinfer1::DataType::kINT32 && nbDims == 1) && "Cannot perform gather on a shape tensor!"

**Comment by bamtercelboo** [comment]
这个没有试过
