### ISSUE TITLE
I have reproduced your code, nothing has been modified, why is my best result p=10.3%, r=13.5%,f=11.7%

### ISSUE THREAD

**Issue by feiyangdezhu** [bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF#3]
I have reproduced your code, nothing has been modified, why is my best result p=10.3%, r=13.5%,f=11.7%

**Comment by bamtercelboo** [comment]
reproduce my code? rewrite?

**Comment by bamtercelboo** [comment]
@feiyangdezhu 
Hi,
Not all the Data is under the Data directory, just the sample Data. Please use all the BMES Data.
