### ISSUE TITLE
CRF的问题

### ISSUE THREAD

**Issue by xguojing** [bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF#8]
你好，有个问题请教。在Sequence_Label.py文件中前向传播函数没看懂，crf层是怎么参与前向传播的？

**Comment by bamtercelboo** [comment]
在训练的时候采用crf（trainer.py, https://github.com/bamtercelboo/pytorch_NER_BiLSTM_CNN_CRF/blob/master/trainer.py#L66）
